version: "1"
services:
  my-container:
      depends_on:
        - rabbitmq
      networks:
        - rabbit-network
      image: server
      ports:
        - 8080:3500
      volumes:
        - /home/ducbui/Documents/UIT/nine-dash:/usr/src/app
      command: sh -c "sleep 10 && npm start"
      restart: unless-stopped
      healthcheck:
        test: wget --quiet --tries=1 --spider http://localhost:3500 || exit 1z
        interval: 30s
        timeout: 10s
        retries: 5
  rabbitmq:
    image: dubc/rabbitmq-alpine-all-plugins
    ports:
      - 5672:5672
    networks:
      - rabbit-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  
networks:
  rabbit-network:
    driver: bridge

  
   
# version: "3"
# services:
#   my-container:
#     image: server
#     ports:
#       - 8080:3500
#     volumes:
#       - /home/ducbui/Documents/UIT/nine-dash:/usr/src/app
#     depends_on:
#       - rabbitmq

#   rabbitmq:
#     image: rabbitmq:latest
#     ports:
#       - 5672:5672
#       - 15672:15672
